[package]
name = "bean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
once_cell = "1.19.0"
serde = "1.0.198"
serde_json = "1.0.117"